/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Debug Exception and Monitor Control Register base address
#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )

void ITM_SendChar(uint8_t ch)
{

	//Enable TRCENA
	DEMCR |= ( 1 << 24);

	//enable stimulus port 0
	ITM_TRACE_EN |= ( 1 << 0);

	// read FIFO status in bit [0]:
	while(!(ITM_STIMULUS_PORT0 & 1));

	//Write to ITM stimulus port0
	ITM_STIMULUS_PORT0 = ch;
}

int _write(int file, char *ptr, int len)
{
  /* Implement your write code here, this is used by puts and printf for example */
  int i=0;
  for(i=0 ; i<len ; i++)
    ITM_SendChar((*ptr++));
  return len;
}

void my_delay(uint32_t ms)
{
	for (uint32_t i = 0; i < ms; i++);
}


void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

#define TASK_STACK_SIZE			4096U
#define SCHE_STACK_SIZE			1024U
#define SRAM_START_ADDR			0x20000000U
#define SRAM_SIZE				(127 * 1024)
#define SRAM_END_ADDR			(SRAM_START_ADDR + SRAM_SIZE)

#define T1_START_STACK			(SRAM_END_ADDR)
#define T2_START_STACK			(T1_START_STACK - TASK_STACK_SIZE)
#define T3_START_STACK			(T2_START_STACK - TASK_STACK_SIZE)
#define T4_START_STACK			(T3_START_STACK - TASK_STACK_SIZE)
#define SCHE_START_STACK		(T4_START_STACK - TASK_STACK_SIZE)

#define SYST_CSR				(0xE000E010UL)	/* SysTick Control and Status Register */
#define SYST_RVR				(0xE000E014UL)	/* SysTick Reload Value Register */
#define SYST_CVR				(0xE000E018UL)	/* SysTick Current Value Register */


#define TASK_STATUS_SIZE		100U
#define T1_MSP_ADDR				(SRAM_END_ADDR - TASK_STATUS_SIZE)
#define T2_MSP_ADDR				(T1_MSP_ADDR - TASK_STATUS_SIZE)
#define T3_MSP_ADDR				(T2_MSP_ADDR - TASK_STATUS_SIZE)
#define T4_MSP_ADDR				(T4_MSP_ADDR - TASK_STATUS_SIZE)

typedef void (*task_handler)();
uint32_t* task_psp[5] = {0,   (uint32_t*)T1_START_STACK - 8
							, (uint32_t*)T2_START_STACK - 8
							, (uint32_t*)T3_START_STACK - 8
							, (uint32_t*)T4_START_STACK - 8};

int main(void)
{

	uint32_t* p_rvr = (uint32_t*)SYST_RVR;
	*p_rvr &= ~(0xFFFFFF);
	*p_rvr = 2000000 - 1;
	uint32_t* p_cvr = (uint32_t*)SYST_CVR;
	*p_cvr |= 1;
	uint32_t* p_csr = (uint32_t*)SYST_CSR;
	*p_csr |= (0x3);

//	uint32_t* task1_handler = task1_handler;


//	__asm volatile ("STR R1, [R0]");

	uint32_t stask_stack_addr[5] = {0, T1_START_STACK, T2_START_STACK, T3_START_STACK, T4_START_STACK};
	task_handler task_handlers[5] = {0, task1_handler, task2_handler, task3_handler, task4_handler};
	for (uint8_t i = 1; i < 5; i++)
	{
		__asm volatile (
		 "MOV R0, %0"
		 :
		 : "r" (stask_stack_addr[i])
		);
		//	__asm volatile ("LDR R0, =0x2001FFFC");
		__asm volatile ("MSR PSP, R0");
		__asm volatile ("MOV R0, #2");
		__asm volatile ("MSR CONTROL, R0");
		__asm volatile ("LDR R1, =0x01000000");
//		__asm volatile ("MOV R0, PC");
		__asm volatile (
		 "MOV R0, %0"
		 :
		 : "r" (task_handlers[i])
		);
		__asm volatile ("PUSH {R0, R1}");
		__asm volatile ("PUSH {R12, R3, R2, R1, R0, LR}");
	}

	task4_handler();
//
//	 __asm volatile ("PUSH {LR, R12, R3, R2, R1, R0}");

//	volatile int x = 3;
//	volatile int y = 4;
//    /* Loop forever */
//	for(;;)
//	{
//		x++;
//		y++;
//		printf("Hello\n");
//	}
}

void SysTick_Handler(void)
{
	static uint8_t task_x = 0;
	/* select task */
	task_x = (task_x) % 4 + 1;
	printf("Task %u will be executed\n", task_x);
	if (1 == task_x)
	{
		/* only need to modify the PSP */
		/* un-stacking operation will get the status of task from PSP */

		/* store the status of previous task */
		__asm volatile (
		 "MRS %0, PSP"
		 : "=r" (task_psp[4])
		);
		/* load the status of next task */
		__asm volatile (
		 "MOV R0, %0"
		 :
		 : "r" (task_psp[1])
		);
		__asm volatile ("MSR PSP, R0");
	}
	else if (2 == task_x)
	{
		__asm volatile (
		 "MRS %0, PSP"
		 : "=r" (task_psp[1])
		);
		__asm volatile (
		 "MOV R0, %0"
		 :
		 : "r" (task_psp[2])
		);
		__asm volatile ("MSR PSP, R0");
	}
	else if (3 == task_x)
	{
		__asm volatile (
		 "MRS %0, PSP"
		 : "=r" (task_psp[2])
		);
		__asm volatile (
		 "MOV R0, %0"
		 :
		 : "r" (task_psp[3])
		);
		__asm volatile ("MSR PSP, R0");
	}
	else if (4 == task_x)
	{
		__asm volatile (
		 "MRS %0, PSP"
		 : "=r" (task_psp[3])
		);
		__asm volatile (
		 "MOV R0, %0"
		 :
		 : "r" (task_psp[4])
		);
		__asm volatile ("MSR PSP, R0");
	}
	printf("An exception occurred!\n");
}

void task1_handler(void)
{
	while (1)
	{
		printf("Hello from task 1\n");
		my_delay(50000);
	}
}

void task2_handler(void)
{
	while (1)
	{
		printf("Hello from task 2\n");
		my_delay(50000);
	}
}

void task3_handler(void)
{
	while (1)
	{
		printf("Hello from task 3\n");
		my_delay(50000);
	}
}

void task4_handler(void)
{
	while (1)
	{
		printf("Hello from task 4\n");
		my_delay(50000);
	}
}
